export const Users = [
  {
    username: 'many92',
    password: 'Many92*+',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'many92@gmail.com',
    roles: ['administrador'],
  },
  {
    username: 'Hannah',
    password: 'Knight',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'hannahknight@digiprint.com',
    roles: ['administrador'],
  },
  {
    username: 'Cain',
    password: 'Wynn',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'cainwynn@digiprint.com',
    roles: ['administrador'],
  },
  {
    username: 'Ford',
    password: 'Wallace',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'fordwallace@digiprint.com',
    roles: ['especialista'],
  },
  {
    username: 'Mallory',
    password: 'Shepard',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'malloryshepard@digiprint.com',
    roles: ['especialista'],
  },
  {
    username: 'Lara',
    password: 'Torres',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'laratorres@digiprint.com',
    roles: ['especialista'],
  },
  {
    username: 'Dollie',
    password: 'Wagner',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'dolliewagner@digiprint.com',
    roles: ['especialista'],
  },
  {
    username: 'Gwendolyn',
    password: 'Robertson',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'gwendolynrobertson@digiprint.com',
    roles: ['laboratorista'],
  },
  {
    username: 'Rodriquez',
    password: 'Vazquez',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'rodriquezvazquez@digiprint.com',
    roles: ['laboratorista'],
  },
  {
    username: 'Petty',
    password: 'Lowery',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'pettylowery@digiprint.com',
    roles: ['laboratorista'],
  },
  {
    username: 'Jones',
    password: 'Hull',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'joneshull@digiprint.com',
    roles: ['laboratorista'],
  },
  {
    username: 'Christensen',
    password: 'Dale',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'christensendale@digiprint.com',
    roles: ['laboratorista'],
  },
  {
    username: 'Jan',
    password: 'Ball',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'janball@digiprint.com',
    roles: ['director'],
  },
  {
    username: 'Roslyn',
    password: 'Phillips',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'roslynphillips@digiprint.com',
    roles: ['director'],
  },
  {
    username: 'Carlson',
    password: 'Tate',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'carlsontate@digiprint.com',
    roles: ['director'],
  },
  {
    username: 'Catherine',
    password: 'Conner',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'catherineconner@digiprint.com',
    roles: ['director'],
  },
  {
    username: 'Madden',
    password: 'Hughes',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'maddenhughes@digiprint.com',
    roles: ['director'],
  },
  {
    username: 'Patton',
    password: 'Page',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'pattonpage@digiprint.com',
    roles: ['especialista_principal'],
  },
  {
    username: 'Constance',
    password: 'Rivers',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'constancerivers@digiprint.com',
    roles: ['especialista_principal'],
  },
  {
    username: 'Perkins',
    password: 'Rowe',
    activo: false,
    avatar: 'http://placehold.it/32x32',
    email: 'perkinsrowe@digiprint.com',
    roles: ['especialista_principal'],
  },
  {
    username: 'Howard',
    password: 'Joyce',
    activo: true,
    avatar: 'http://placehold.it/32x32',
    email: 'howardjoyce@digiprint.com',
    roles: ['especialista_principal'],
  },
];
